// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDftZoG1e1PNLwey8Fv6SQhVmopEM-cmbo',
    appId: '1:56701802004:web:43ede6efeda6bacaa0f901',
    messagingSenderId: '56701802004',
    projectId: 'onlinevotingsystem-ee812',
    authDomain: 'onlinevotingsystem-ee812.firebaseapp.com',
    storageBucket: 'onlinevotingsystem-ee812.appspot.com',
    measurementId: 'G-S3QX3YVRHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSxwabzcbW8nwXTKXWKzsc4juiaIeoHUM',
    appId: '1:56701802004:android:547cb871dcd5a724a0f901',
    messagingSenderId: '56701802004',
    projectId: 'onlinevotingsystem-ee812',
    storageBucket: 'onlinevotingsystem-ee812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfNsz0wLvpaGInuAt2vC-zNbUcrYwxeZA',
    appId: '1:56701802004:ios:10c014d81aeac9daa0f901',
    messagingSenderId: '56701802004',
    projectId: 'onlinevotingsystem-ee812',
    storageBucket: 'onlinevotingsystem-ee812.appspot.com',
    iosBundleId: 'com.example.onlineVotingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfNsz0wLvpaGInuAt2vC-zNbUcrYwxeZA',
    appId: '1:56701802004:ios:d1acd38fb1473a3fa0f901',
    messagingSenderId: '56701802004',
    projectId: 'onlinevotingsystem-ee812',
    storageBucket: 'onlinevotingsystem-ee812.appspot.com',
    iosBundleId: 'com.example.onlineVotingSystem.RunnerTests',
  );
}
