// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOW49MAa1b3iaH8EqEVLH8X6R1Tulz1xU',
    appId: '1:771612945089:web:f67c703fb30ea098b4c240',
    messagingSenderId: '771612945089',
    projectId: 'onlineurjitsystem',
    authDomain: 'onlineurjitsystem.firebaseapp.com',
    storageBucket: 'onlineurjitsystem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4EEy6jYgeRnps9tMBXSInv7sHbtxklXg',
    appId: '1:771612945089:android:fe210b559517fa6bb4c240',
    messagingSenderId: '771612945089',
    projectId: 'onlineurjitsystem',
    storageBucket: 'onlineurjitsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjgWuO6GhFJ_3Fl1k4ESvHffvs0BEaT7E',
    appId: '1:771612945089:ios:7e24ca01d2e310b5b4c240',
    messagingSenderId: '771612945089',
    projectId: 'onlineurjitsystem',
    storageBucket: 'onlineurjitsystem.appspot.com',
    iosClientId: '771612945089-jdmvqqe843ied3q4vp5o8ujfeefppgsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineVotingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjgWuO6GhFJ_3Fl1k4ESvHffvs0BEaT7E',
    appId: '1:771612945089:ios:32d21d9f150624f8b4c240',
    messagingSenderId: '771612945089',
    projectId: 'onlineurjitsystem',
    storageBucket: 'onlineurjitsystem.appspot.com',
    iosClientId: '771612945089-mb0nujso0oi29od8jn4lvuvujgk8fcba.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineVotingSystem.RunnerTests',
  );
}
